---
title: "Rtistry"
description: | 
  Generative art created in R
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(flametree)
```

### Miscellaneous Art
```{r}
seq(-4, 4, by = 0.02) %>% 
  expand.grid(x = ., y = .) %>% 
  ggplot()+
  geom_point(mapping = aes(x = (1+abs(y)-sin(x^2)), y = 1-x+cos(y^2)),
             alpha = 0.05, shape = 20, size = 1, color = "red")+
  theme_void()+
  coord_polar()
```

### [{flametree}](https://flametree.djnavarro.net/index.html)
An R package for generative art by [djnavarro](https://djnavarro.net)

```{r}
flametree_grow(
  time = 8,
  trees = 6,
  split = 2,
  shift_x = spark_random(multiplier = 5),
  seg_col = spark_linear(tree =2, time = 1)
  ) %>% 
  flametree_plot(
    palette = c("#801100", "#B62203", "#D73502", "#FC6400", "#FF7500", "#FAC000")  
    )
```

```{r}
flametree_grow(seed = 213, 
               time = 10, 
               scale = c(0.5, 1.5),
               angle = c(-30, 10),
               split = 2,
) %>% 
  flametree_plot(
    palette = c("cadetblue",
                "blue",
                "cyan",
                "darkslateblue")
) 
```

```{r}
plot <- flametree_grow(seed = 213, 
                       time = 6, 
                       scale = c(0.25, 0.50, 0.75, 1.0, 1.5),
                       angle = c(-30, -15, 10, 20),
                       split = 3,
                       trees = 4,
                       shift_x = spark_linear(tree = 4),
                       shift_y = spark_linear(tree = 3)
) %>% 
  flametree_plot(
    palette = c("cadetblue",
                "blue",
                "cyan",
                "darkslateblue")
  )

plot+coord_polar()
```

