---
title: "Stat 231: Introductory Statistics"
description: | 
  Course materials for Stat 231
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Goals

This is a first course in statistics designed for non-STEM majors. An emphasis is placed on a broad understanding of topics in sampling methods, basic probability, hypothesis testing, confidence intervals and linear regression. Students will also be introduced to statistical computing.

## Course Materials

Our textbook is [OpenIntro Statistics: 4th Ed.](https://www.openintro.org/book/os).

A graphing calculator will be useful for some of the computations we will do. Specifically instruction will be provided for the Ti-83/84 and Casio FX-750GII. 

We will have a total of seven computer labs using R and RStudio. There will be dedicated class time to installing the software or setting up a cloud account. Those who feel comfortable doing so can download [R](https://cran.r-project.org) and [RStudio](https://www.rstudio.com/download) prior to the start of class.

The weekly schedule and other resources can be found on our Sakai site. 

## R Package 
All materials needed for lab days can be found in the [Stat231](https://www.github.com/npaterno/Stat231) R package. Students can install the package by running the code below in the console of RStudio (requires the `remotes`` package). As with R and RStudio, there will be dedicated time in class for this activity. 

> install.packages("remotes")

> remotes::install_github("npaterno/stat231", build_vignettes = TRUE)

Each lesson can be found as a vignette in the help file. The corresponding assignments are available as RMarkdown templates. 

[Slides](https://npaterno.github.io/left_coast_stats/slides) related to the labs and/or in class lectures can be found here. 